### ISSUE TITLE
Add contact link to website

### ISSUE THREAD

**Issue by sergefdrv** [replica-io/replica-io.github.io#13]
Add a mailto link to the website footer. The email to use: "contact" at domain name (replica-io.dev). To add some level of spam protection, obfuscate the email, e.g. using the [`botex`](https://www.npmjs.com/package/botex) package.

It would also be nice to add an email link to the navigation bar using the [regular envelope icon](https://fontawesome.com/icons/envelope?f=classic&s=regular) from Font Awesome.

**Comment by adrianvrj** [comment]
Hi, can I help with this?

**Comment by sergefdrv** [comment]
@adrianvrj Getting some help with the website would be nice! Would you mind joining [our Discord server](https://discord.replica-io.dev/)?

**Comment by adrianvrj** [comment]
> @adrianvrj Getting some help with the website would be nice! Would you mind joining [our Discord server](https://discord.replica-io.dev/)?

sure, no problem!

**Comment by frozenmafia** [comment]
Here is the [PR](https://github.com/replica-io/replica-io.github.io/pull/31) for this issue.

**Comment by sergefdrv** [comment]
Resolved in #34
